version: '3'

services:
  redis:
    image: redislabs/redismod:latest
    # image: myredis
    container_name: redis
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - ./redis_data:/data

  insight:
    image: "redislabs/redisinsight:latest"
    container_name: insight
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db
    depends_on:
      - redis

  flask:
    image: webapp-flask
    container_name: flask
    environment:
      - REDIS_SERVER=redis
      - REDIS_PORT=6379
      - TICKER_FILE_LOCATION=/data/daily/us/nysemkt stocks
      - PROCESSES=6
      - PYTHONBUFFERED=0
      - WRITE_JSON=false
      - PROCESS_DATES=true
      - PROCESS_RECENTS=false
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - '5000:5000'
    volumes:
      - "./src/:/app"
      - "./data/:/data"
    depends_on:
      - redis
